name: Deploy Library

on:
  release:
    types:
      - published

jobs:
  deploy_cocoapods:
    runs-on: 'macOS-15'
    steps:
      - uses: actions/checkout@v4
      - name: "Run Local Action: Setup Machine"
        uses: ./.github/workflows/setup-machine
      - name: Deploy to Cocoapods
        run: scripts/publish.sh -p
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}